### Admin login
POST {{host}}/api/login
Content-Type: Application/json

{
    "username": "admin@test.com",
    "password": "1"
}

### member login
POST {{host}}/api/login
Content-Type: Application/json

{
    "username": "user@test.com",
    "password": "1"
}

### Get all members
GET {{host}}/admin/members
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiaWF0IjoxNjczNTIwODcwLCJleHAiOjE2NzYxNDg4NzB9.Uai2k9-iw9fSMGahFvsJ2xBF4hfR8VhNdprOS6_efYzq2hhWRLgkNAZO0epOMOk5ImeygLFWA6Cwcto5N7dX0g

### Join Member
POST {{host}}/api/join
Content-Type: Application/json

{
    "name": "kenux1",
    "email": "user1@test.com",
    "password": "password"
}

### Get member detail
GET {{host}}/api/member/2
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJ1c2VyQHRlc3QuY29tIiwiYXV0aCI6IlJPTEVfVVNFUiIsImlhdCI6MTY3MzUyMDg4MSwiZXhwIjoxNjc2MTQ4ODgxfQ.SUp-GTuC6yi9vbr__-Alaq2X9JT0X5_38PNLFx1o8OPkv2_eGKIipNxkTNJ8_R6bk8ABcR5vMvmHjAYP_iOdlg
