spring:
  profiles:
    group:
      "local": "common, logging, h2DB"
      "dev": "common, logging, mariaDB-test"
      "prd": "common, mariaDB"
    default: local
---
spring:
  config:
    activate:
      on-profile: h2DB
  datasource:
    url:  jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
#      max-lifetime: 30000
#      idle-timeout: 20000
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#    generate-ddl: false
#      database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: mariaDB-test
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/test
    username: kenux
    password: ENC(aHa2RW3L77g852hK+TDN97K6Gr/XxEJ8p/MnOcQsXCg=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
---
spring:
  config:
    activate:
      on-profile: mariaDB-dev
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/travel_log_db
    username: kenux
    password: ENC(aHa2RW3L77g852hK+TDN97K6Gr/XxEJ8p/MnOcQsXCg=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
  messages:
    basename: messages/messages
  output:
    ansi:
      enabled: always
  mvc:
    log-request-details: true
jasypt:
  encryptor:
    bean: encryptorBean
app:
  jwt:
    secret: ENC(9lN6TSY60ahFOftfOVIQ3oOVa20379X5pmDFXlTlPM9QE6gQhFKxEAfdvEw5WvmieXu/JoBS0zZ/BBTBckJmHwmwWFUzU6iDLh1u4HS+RYS1DGpXbcqoymzy0wI+4yl5tVM9DH0tV9cvpdS2Z0+Sbw==)
    tokenExpiration:  300000 # 5min
    refreshTokenExpiration: 1800000 # 30min
---
spring:
  config:
    activate:
      on-profile: logging
logging:
  level:
    org:
      hibernate:
        resource:
          transaction: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
        security: debug
        web: debug
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
