spring:
  config:
    activate:
      on-profile: prd
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/travel_log_db
    username: kenux
    password: ENC(aHa2RW3L77g852hK+TDN97K6Gr/XxEJ8p/MnOcQsXCg=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
