spring:
  profiles:
    group:
      "test": "h2DB, common"
      "test1": "h2DB-mysql, common"
      "local": "h2DB-server, common"
      "dev": "mariaDB, common"
      "prd": "prddb, common"
---
spring:
  config:
    activate:
      on-profile: h2DB
  datasource:
    url:  jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect
    #    database: h2
    generate-ddl: false
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: h2DB-mysql
  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    url:  jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#    database: h2
    generate-ddl: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: h2DB-server
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
#    locations: classpath:/db/migration
---
spring:
  config:
    activate:
      on-profile: common
  output:
    ansi:
      enabled: always
#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace


