spring:
  profiles:
    group:
      "test": "h2DB, common, dev-logging"
      "test1": "h2DB-mysql, common, dev-logging"
      "local": "h2DB-server, common, dev-logging"
      "dev": "mariaDB, common"
      "prd": "prddb, common"
    active: test
---
spring:
  config:
    activate:
      on-profile: h2DB
  datasource:
    url:  jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
#        dialect: org.hibernate.dialect.MariaDBDialect
    #    database: h2
    generate-ddl: false
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: h2DB-mysql
  datasource:
#    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    url:  jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
#    database: h2
    generate-ddl: false
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
---
spring:
  config:
    activate:
      on-profile: h2DB-server
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
#    locations: classpath:/db/migration
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: always
---
spring:
  config:
    activate:
      on-profile: dev-logging
logging:
  level:
    org:
      hibernate:
        resource:
          transaction: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
server:
  error:
    whitelabel:
      enabled: false
