spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/test
    username: kenux
    password: ENC(YXeVMjeJ2XWyLbPgQahNDiqRoQcJFHyfRJE23O59ugJ5+huwqUgLUyERwA0iUVKd)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
