---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test2
    driver-class-name: org.h2.Driver
    username: sa
---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  output:
    ansi:
      enabled: always

  # flyway
  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:/db/migration

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace


