spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
    properties:
      hibernate:
        default_batch_fetch_size: 1000
  messages:
    basename: messages/messages
  output:
    ansi:
      enabled: always
  mvc:
    log-request-details: true
jasypt:
  encryptor:
    bean: jasyptStringEncryptor
app:
  jwt:
    secret: ENC(o6rMmfcVSi6t3HKRQ6Tjpnwh0LDVKN8lnM2W+ZvSOjjsZMSKY71qPvHOvO7POjFpza5rsklH2UBbIhy02JNrzBDls82i33TtdpebWC9xfncHy64KqxSzgs6b5NdRtt4nhihmP2Hmtei0czmrmzvA3BmWSPAlIFOzN8AFocdBp0U=)
    tokenExpiration:  300000 # 5min 300000
    refreshTokenExpiration: 1800000 # 30min 1800000
