spring:
  config:
    activate:
      on-profile: actuator
management:
  endpoints:
    enabled-by-default: false
    web:
      exposure:
        include: "*"
  endpoint:
    env:
      enabled: true
    flyway:
      enabled: true
    beans:
      enabled: true
    info:
      enabled: true