spring:
  profiles:
    group:
      "test": "common, logging, h2DB"
      "dev": "common, logging, mariaDB-test"
      "prd": "common, mariaDB"
    active: test
---
spring:
  config:
    activate:
      on-profile: h2DB
  datasource:
#    url:  jdbc:h2:mem:testdb;DATABASE_TO_LOWER=TRUE
    url:  jdbc:h2:mem:testdb;MODE=MySQL;DATABASE_TO_LOWER=TRUE
    driver-class-name: org.h2.Driver
    username: sa
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.MariaDBDialect
    generate-ddl: false
  #    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  flyway:
    enabled: false
server:
  port: 8088
---
spring:
  config:
    activate:
      on-profile: mariaDB-test
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/test
    username: kenux
    password: ENC(aHa2RW3L77g852hK+TDN97K6Gr/XxEJ8p/MnOcQsXCg=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
jasypt:
  encryptor:
    bean: encryptorBean
---
spring:
  config:
    activate:
      on-profile: mariaDB-dev
  datasource:
    url: jdbc:mariadb://kenux.duckdns.org:3306/travel_log_db
    username: kenux
    password: ENC(aHa2RW3L77g852hK+TDN97K6Gr/XxEJ8p/MnOcQsXCg=)
    driver-class-name: org.mariadb.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: false
        show_sql: false
  flyway:
    enabled: false
#    baseline-on-migrate: true
#    baseline-version: 0
jasypt:
  encryptor:
    bean: encryptorBean
---
spring:
  config:
    activate:
      on-profile: common
  jpa:
    open-in-view: false
  output:
    ansi:
      enabled: always
server:
  error:
    whitelabel:
      enabled: false
---
spring:
  config:
    activate:
      on-profile: logging
logging:
  level:
    org:
      hibernate:
        resource:
          transaction: DEBUG
        type:
          descriptor:
            sql: trace
      springframework:
        transaction:
          interceptor: TRACE
        orm:
          jpa:
            JpaTransactionManager: DEBUG
        jdbc:
          datasource:
            DataSourceTransactionManager: DEBUG
    com.zaxxer.hikari: TRACE
    com.zaxxer.hikari.HikariConfig: DEBUG
