---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test2
    driver-class-name: org.h2.Driver
    username: sa
---
spring:
  config:
      activate:
        on-profile: local
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
#    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql: true
        show_sql: true
  output:
    ansi:
      enabled: always

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace


