---
spring:
  config:
    activate:
      on-profile: develop
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/travelog
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    #    show-sql: true
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  output:
    ansi:
      enabled: always
  flyway:
    enabled: true
    baseline-on-migrate: true
    baseline-version: 0
#    locations: classpath:/db/migration

---
spring:
  config:
    activate:
      on-profile: default
  datasource:
    url: jdbc:h2:tcp://localhost/~/h2dbs/test
    driver-class-name: org.h2.Driver
    username: sa
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql: true
    generate-ddl: false
  output:
    ansi:
      enabled: always
  flyway:
    enabled: false

#logging:
#  level:
#    org:
#      hibernate:
#        type:
#          descriptor:
#            sql: trace


