### Admin login
POST {{host}}/api/auth/login
Content-Type: Application/json

{
    "username": "{{username-admin}}",
    "password": "{{password}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### member login
POST {{host}}/api/auth/login
Content-Type: Application/json

{
    "username": "{{username-user}}",
    "password": "{{password}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
 %}

### 로그아웃
POST {{host}}/api/auth/logout
Content-Type: Application/json
Authorization: Bearer {{accessToken}}

### login failed - member not exist
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "ghost@test.com",
    "password": "123123"
}

### login failed - wrong password
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "{{username-user}}",
    "password": "123123"
}

### 미인증 접근
GET {{host}}/admin/member
Authorization: Bearer {{accessToken}}
