### Admin login
POST {{host}}/api/auth/login
Content-Type: Application/json

{
    "username": "{{username-admin}}",
    "password": "{{password-admin}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### member login
POST {{host}}/api/auth/login
Content-Type: Application/json

{
    "username": "{{username-user}}",
    "password": "{{password-user}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
 %}

### 로그아웃
POST {{host}}/api/auth/logout
Content-Type: Application/json
Authorization: Bearer {{accessToken}}

### login failed - member not exist
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "ghost@test.com",
    "password": "123123"
}

### login failed - wrong password
POST {{host}}/api/auth/login
Content-Type: application/json

{
    "username": "{{username-user}}",
    "password": "123123"
}

### 접근권한 없는 경우 -> 403
GET {{host}}/admin/member
Authorization: Bearer {{accessToken}}

### expired access token
GET {{host}}/admin/member
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJzdWIiOiJhZG1pbkB0ZXN0LmNvbSIsImF1dGgiOiJST0xFX0FETUlOIiwiZXhwIjoxNjc1MDc5NjM1fQ.Dh7-mAaVLe6jS94AdnVKdwnzMuhvIPGBWZATeykc-_V7ib-sAwXCqy1MMBjWKIzontQpkPzfjI7MpmmJGn238A

### refresh access token
POST {{host}}/api/auth/refreshToken
Content-Type: application/json

{
    "token": "{{refreshToken}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
%}
