### Join Member
POST {{host}}/api/signup
Content-Type: Application/json

{
    "name": "kenux1",
    "email": "kenux1@test.com",
    "password": "password"
}

### member login
POST {{host}}/api/auth/login
Content-Type: Application/json

{
    "username": "{{username-user}}",
    "password": "{{password-user}}"
}

> {%
    client.global.set("accessToken", response.body.accessToken);
    client.global.set("refreshToken", response.body.refreshToken);
%}

### Get member detail
GET {{host}}/api/members/2
Authorization: Bearer {{accessToken}}

### Get my simple info
GET {{host}}/api/members/me?id=2
Authorization: Bearer {{accessToken}}