create table travel_history
(
    id             bigint generated by default as identity,
    created_date   timestamp,
    updated_date   timestamp,
    created_by     varchar(255),
    updated_by     varchar(255),
    content        varchar(255),
    end_date       date,
    start_date     date,
    title          varchar(255),
    travel_type    varchar(255),
    destination_id bigint,
    primary key (id)
);

create table travel_history_comment
(
    id                bigint generated by default as identity,
    comment           varchar(255),
    parent_id         bigint,
    comment_id        bigint,
    travel_history_id bigint,
    primary key (id)
);

alter table travel_history
    add constraint travel_history_destination_fk
        foreign key (destination_id)
            references destination;

alter table travel_history_comment
    add constraint travel_history_comment_parent_child_fk
        foreign key (comment_id)
            references travel_history_comment;

alter table travel_history_comment
    add constraint travel_history_comment_travel_history_fk
        foreign key (travel_history_id)
            references travel_history
