create table destination
(
    id          bigint generated by default as identity,
    address     varchar(255),
    information varchar(255),
    name        varchar(255),
    primary key (id)
);

create table password
(
    member_name  varchar(255) not null,
    created_date timestamp,
    updated_date timestamp,
    password     varchar(255),
    primary key (member_name)
);

create table start_point
(
    id             bigint generated by default as identity,
    star_point     integer,
    destination_id bigint,
    primary key (id)
);

alter table start_point
    add constraint start_point_destination_fk
        foreign key (destination_id)
            references destination;
